version: '3.8'

services:
  bun:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - bun_uploads:/app/uploads
      - bun_previews:/app/previews

volumes:
  bun_uploads:
  bun_previews:
